import type { NextPage } from "next";
import Head from "next/head";
import MainContainer from "src/containers/MainContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer />
    </div>
  );
};

export default Home;
