import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import React from "react";
import MainContainer from "src/containers/MainContainer";
import wrapper from "src/store/configureStore";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

type Props = {};

const Home: NextPage = (props) => {
  // console.log(props);
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer />
    </React.Fragment>
  );
};

export default Home;

export const getStaticProps = wrapper.getStaticProps(
  (store) => async (ctx: GetStaticPropsContext) => {
    const { locale } = ctx;

    try {
      return {
        props: {
          ...(await serverSideTranslations(locale as string, ["common"])),
        },
      };
    } catch (error) {
      return {
        props: {},
      };
    }
  }
);
